[package]
name = "aoclib"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"
documentation = "https://aoclib-docs.netlify.app/aoclib/"

[dependencies]
bitvec = "0.20.1"
dirs = "3.0.1"
gif = { version = "0.11.1", optional = true }
itertools = "0.10.0"
lazy_static = "1.4.0"
num = "0.3.1"
parse-display = "0.4.0"
rand = { version = "0.8.0", optional = true }
regex = "1.4.2"
reqwest = { version = "0.10.10", features = [ "blocking", "gzip", "cookies" ] }
serde = { version = "1.0.118", features = [ "derive" ] }
serde_with = "1.8.1"
smallstr = "0.2.0"
thiserror = "1.0.22"
toml = "0.5.8"

[features]
map-render = [ "gif", "rand" ]
