[package]
name = "aoclib"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"
documentation = "https://aoclib-docs.netlify.app/aoclib/"

[dependencies]
bitvec = "1.0.1"
dirs = "4.0.0"
gif = { version = "0.11.4", optional = true }
itertools = "0.10.5"
lazy_static = "1.4.0"
num = "0.4.0"
parse-display = "0.6.0"
rand = { version = "0.8.5", optional = true }
regex = "1.6.0"
reqwest = { version = "0.11.12", features = [ "blocking", "gzip", "cookies" ] }
serde = { version = "1.0.145", features = [ "derive" ] }
serde_with = "2.0.1"
smallstr = "0.3.0"
thiserror = "1.0.37"
toml = "0.5.9"

[dev-dependencies]
derive_more = "0.99.17"

[features]
map-render = [ "gif", "rand" ]
